Debug = true

[User]
OpenRegister = true

[Node]
NodeName = ''

[File]
SavePath = '../store/cache/'
MaxSize = 200                    #Company: M
MaxAge = 5                       #File retention time: days

[Log]
Path = '../store/log/app.log'
Level = 'debug'
MaxSize =  200                   #Maximum size saved per log file unit: M
MaxNum = 1000                    #How many log files can be saved at most
MaxAge = 30                      #How many days can the log file be saved at most

[Token]
Key = 'ChYzvtt8ixVbM%Eo'         #Token key
StartDuration = 0                #How long will the token take effect (hours, 0: immediately)
StopDuration = 1000              #How long after the token takes effect (hours, 0: immediate)

[DB]
Name = 'sqlite'
Connect = '../store/db/manage.db'
MaxConn =  0                     #Maximum number of connections, 0 means unlimited
MaxKeepConn = 2                  #Maximum number of connections maintained (long connections)
MaxLifeTime = 21                 #Database request timeout (seconds, 0: for immediate rejection)

[Grpc]
ListenAddr = ':888'
PublicKeyPath = '../store/cert/grpc/server_cert.pem'
PrivateKeyPath = '../store/cert/grpc/server_key.pem'

[Http]
ShowLog = false
UseHttps = false
ListenAddr = '0.0.0.0:80'

[Http.Https]
RedirectAddr = '0.0.0.0:80'      #Redirect HTTP to HTTPS
PublicKeyPath = '../store/cert/https/public.pem'
PrivateKeyPath = '../store/cert/https/private.key'

[Http.WebSocket]
ReadWaitTime = 0        #Read request timeout (seconds, 0: Forever timeout, negative: immediate timeout)
WriteWaitTime = 5       #Write request timeout (seconds, 0: Forever timeout, negative: immediate timeout)
PingWaitTime = 0        #Ping request timeout (seconds, 0: timeout forever, negative: timeout immediately)
PongWaitTime = 0        #Pong request timeout (seconds, 0: timeout forever, negative: timeout immediately)

[Http.Files]
Web = './web'



